image:
    file: .gitpod.dockerfile

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
tasks:
  - init: pip install -r requirements.txt
  - init: pip2 install pygame
    command: python2 main.py

